services:
  app:
    build: .
    container_name: ytplaylistanalyser
    command: gunicorn --reload -b 0.0.0.0:80 src.main:app
    ports:
      - "80:80"
    volumes:
      - .:/code
    # Add any other necessary environment variables or configurations here
    # Optionally, configure volume settings here if needed